### ISSUE TITLE
More detailed metadata for when using "Download your personal data"

### ISSUE THREAD

**Issue by Kovaelin** [meganz/webclient#45]
When looking at the metadata, such as the `files.json` file, it's difficult to retrieve anything useful without some some work first.

The timestamp is in Unix, so I figured that out using a converting tool online. What do the `link_identifier` and `node_identifier` convert to though? Is it possible to retrieve file names?

Thank you.

**Comment by pohutukawa** [comment]
I don't have any connection to Mega, though I did work for them in the past.

Anyway, some comments on your request:

* Mega is presenting itself as a privacy focused company. That is good. They're achieving that by employing strong encryption and *not* having to know too much stuff (which is good, too much knowledge can easily be a burden).
* Due to the encryption schemes used, not even Mega knows the file names of your content. Again, which is good! Therefore, if you ask *them* to give you personal information held for you, they won't know it all. Some of the stuff (including your file paths/names) can only be known to you and are only accessible via knowledge of the correct encryption keys. Again, these are the secret bits that only *you* are holding.
* Timestamps in UNIX Epoch format are a good thing. Especially when dealing with things/people globally, and time zones and all kinds of nasties around them are involved (such things as daylight savings especially).

I'd advise to write a little tool that will augment your data dump with the bits you want to know. Otherwise: be happy they're not too explicit and enriched, as that would also make the same data easily available to everybody else.

Enough for my NZ$ 0.02 ...
