### ISSUE TITLE
Chrome - unable to download file in incognito because the browser automatically closes after ~1GB download

### ISSUE THREAD

**Issue by olekstomek** [meganz/webclient#67]
In the MEGA cloud I have an mp4 file with a size of 5.98 GB. I am downloading this file in incognito mode.
After ~1.10 GB has been downloaded, the browser exits automatically.
I confirmed the problem in:

- Google Chrome 87.0.4280.88 64-bits (Windows 10 64 bit)
- Edge 87.0.664.60 64-bits (Windows 10 64 bit)
- Google Chrome 86.0.4240.111 (Linux Mint 20 64 bit)

![image](https://user-images.githubusercontent.com/26818304/102616400-c9d33180-4137-11eb-81b7-d2a2113a7280.png)

Downloading large files from elsewhere does not cause this behavior.

If the problem occurs in download, it may also occur in upload mode incognito (I haven't checked it).

**Comment by khaleddaifallah-mega** [comment]
Due to the need of decrypting the received data, it might not be possible to download big files in incognito mode. Because of the limited resources available (Storage) in this mode, which makes MEGA switch to memory usage for data buffering.

Therefore, depending on the client running the browser this might lead to download failure or app/browser crash. 

Please use normal session in the bowser (not incognito) if you want to deal with big files (upload/download). Later in order to maintain privacy you can logout.

**Comment by olekstomek** [comment]
Interesting thought. Thanks for that clarification.
